apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - ghcr.io/actions/actions-runner-controller-chart
