apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
  project: default
  source:
    path: cert-manager
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: HEAD
