apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
   name: hra-csa
spec:
#  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    name: k8s-runner-deployment
  minReplicas: 1
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent: {}
    duration: "30s"
