apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  project: actions-runner-controller
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.4.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
